### ISSUE TITLE
Build error when `yarn build-rust`

### ISSUE THREAD

**Issue by saltyshiomix** [LayerXcom/zerochain-wallet-desktop#16]
I want to try this app but unfortunately an error occurred below:

```
🐈💕 yarn build-rust
yarn run v1.21.1
$ electron-build-env neon build --path zerochain --release
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling libc v0.2.66
   Compiling cfg-if v0.1.10
   Compiling byteorder v1.3.2
   Compiling spin v0.5.2
   Compiling proc-macro2 v1.0.7
   Compiling semver-parser v0.7.0
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.13
   Compiling typenum v1.11.2
   Compiling autocfg v0.1.7
   Compiling cc v1.0.50
   Compiling log v0.4.8
   Compiling rand_core v0.4.2
   Compiling maybe-uninit v2.0.0
   Compiling serde v1.0.104
   Compiling opaque-debug v0.2.3
   Compiling byte-tools v0.3.1
   Compiling getrandom v0.1.14
   Compiling nodrop v0.1.14
   Compiling ppv-lite86 v0.2.6
   Compiling fake-simd v0.1.2
   Compiling constant_time_eq v0.1.4
   Compiling subtle v2.2.2
   Compiling rustc-demangle v0.1.16
   Compiling subtle v1.0.0
   Compiling failure_derive v0.1.6
   Compiling keccak v0.1.0
   Compiling futures v0.1.29
   Compiling stable_deref_trait v1.1.1
   Compiling scopeguard v0.3.3
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling memchr v2.2.1
   Compiling syn v0.15.44
   Compiling untrusted v0.6.2
   Compiling byte-tools v0.2.0
   Compiling either v1.5.3
   Compiling regex-syntax v0.6.13
   Compiling arrayvec v0.4.12
   Compiling arrayref v0.3.5
   Compiling safemem v0.3.3
   Compiling slab v0.4.2
   Compiling heapsize v0.4.2
   Compiling crunchy v0.2.2
   Compiling rustc-hex v2.1.0
   Compiling proc-macro-hack-impl v0.4.2
   Compiling hash-db v0.12.4
   Compiling static_assertions v0.2.5
   Compiling fnv v1.0.6
   Compiling memory_units v0.3.0
   Compiling scopeguard v1.0.0
   Compiling hex v0.3.2
   Compiling autocfg v1.0.0
   Compiling smallvec v1.1.0
   Compiling base58 v0.1.0
   Compiling matches v0.1.8
   Compiling hashmap_core v0.1.11
   Compiling percent-encoding v1.0.1
   Compiling environmental v1.1.1
   Compiling integer-sqrt v0.1.2
   Compiling quick-error v1.2.3
   Compiling protobuf v2.10.0
   Compiling data-encoding v2.1.2
   Compiling bs58 v0.2.5
   Compiling zeroize v0.5.2
   Compiling void v1.0.2
   Compiling version_check v0.1.5
   Compiling bitmask v0.5.0
   Compiling itoa v0.4.4
   Compiling wasm-bindgen-shared v0.2.58
   Compiling ryu v1.0.2
   Compiling bitflags v1.2.1
   Compiling httparse v1.3.4
   Compiling bumpalo v3.1.2
   Compiling pkg-config v0.3.17
   Compiling unicode-segmentation v1.6.0
   Compiling wasm-bindgen v0.2.58
   Compiling slog v2.5.2
   Compiling crunchy v0.1.6
   Compiling strum v0.14.0
   Compiling sha1 v0.6.0
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.26
   Compiling core-foundation-sys v0.6.2
   Compiling nohash-hasher v0.1.2
   Compiling byteorder v0.5.3
   Compiling lazycell v1.2.1
   Compiling static_slice v0.0.3
   Compiling c_linked_list v1.1.1
   Compiling parity-send-wrapper v0.1.0
   Compiling take_mut v0.2.2
   Compiling arc-swap v0.4.4
   Compiling remove_dir_all v0.5.2
   Compiling parity-bytes v0.1.0 (https://github.com/paritytech/parity-common?rev=b0317f649ab2c665b7987b8475878fc4d2e1f81d#b0317f64)
   Compiling native-tls v0.2.3
   Compiling language-tags v0.2.2
   Compiling traitobject v0.1.0
   Compiling typeable v0.1.2
   Compiling unicode-width v0.1.7
   Compiling try-lock v0.2.2
   Compiling bit-vec v0.4.4
   Compiling ansi_term v0.11.0
   Compiling strsim v0.7.0
   Compiling cslice v0.2.0
   Compiling termcolor v1.0.5
   Compiling vec_map v0.8.1
   Compiling neon-build v0.3.3
   Compiling lazy_static v1.4.0
   Compiling semver v0.9.0
   Compiling rand_core v0.3.1
   Compiling block-padding v0.1.5
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling crossbeam-utils v0.7.0
   Compiling crossbeam-epoch v0.8.0
   Compiling indexmap v1.3.0
   Compiling c2-chacha v0.2.3
   Compiling owning_ref v0.4.0
   Compiling trie-root v0.12.4
   Compiling tokio-sync v0.1.7
   Compiling lock_api v0.3.3
   Compiling proc-macro-hack v0.4.2
   Compiling backtrace-sys v0.1.32
   Compiling clear_on_drop v0.2.3
   Compiling ring v0.14.6
   Compiling unicode-normalization v0.1.11
   Compiling unicode-bidi v0.3.4
   Compiling humantime v1.3.0
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling error-chain v0.12.1
   Compiling unicase v1.4.2
   Compiling heck v0.3.1
   Compiling openssl-sys v0.9.53
   Compiling foreign-types v0.3.2
   Compiling textwrap v0.10.0
   Compiling thread_local v1.0.0
   Compiling crossbeam-utils v0.6.6
   Compiling thread_local v0.3.6
   Compiling rustc_version v0.2.3
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling lock_api v0.1.5
   Compiling hex-literal-impl v0.1.2
   Compiling idna v0.1.5
   Compiling tokio-executor v0.1.9
   Compiling crossbeam-queue v0.1.2
   Compiling crossbeam-channel v0.3.9
   Compiling quote v1.0.2
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling rand v0.4.6
   Compiling iovec v0.1.4
   Compiling rand v0.5.6
   Compiling num_cpus v1.11.1
   Compiling net2 v0.2.33
   Compiling time v0.1.42
   Compiling get_if_addrs v0.5.3
   Compiling termios v0.3.1
   Compiling atty v0.2.14
   Compiling clicolors-control v1.0.1
   Compiling parking_lot_core v0.7.0
   Compiling dirs-sys v0.3.4
   Compiling dirs v1.0.5
   Compiling base64 v0.9.3
   Compiling parity-wasm v0.31.3
   Compiling hashbrown v0.1.8
   Compiling dns-parser v0.8.0
   Compiling base64 v0.10.1
   Compiling log v0.3.9
   Compiling want v0.2.0
   Compiling parking_lot_core v0.4.0
   Compiling sr-std v1.0.0 (https://github.com/osuketh/substrate?branch=patch-zerochain#12f25052)
   Compiling parking_lot_core v0.6.2
   Compiling sr-io v1.0.0 (https://github.com/osuketh/substrate?branch=patch-zerochain#12f25052)
   Compiling parking_lot v0.9.0
   Compiling memoffset v0.5.3
   Compiling safe-mix v1.0.0
   Compiling snow v0.5.2
   Compiling hyper v0.12.35
   Compiling cast v0.2.3
   Compiling generic-array v0.12.3
   Compiling generic-array v0.8.3
   Compiling generic-array v0.9.0
   Compiling smallvec v0.6.13
   Compiling aho-corasick v0.7.6
   Compiling elastic-array v0.10.3
   Compiling quote v0.6.13
   Compiling uint v0.7.1
   Compiling hash256-std-hasher v0.12.4
   Compiling tiny-keccak v1.5.0
   Compiling blake2-rfc v0.2.18
   Compiling blake2-rfc v0.2.18 (https://github.com/gtank/blake2-rfc?rev=7a5b5fc99ae483a0043db7547fb79a6fa44b88a9#7a5b5fc9)
   Compiling hex-literal v0.1.4
   Compiling url v1.7.2
   Compiling bigint v4.4.1
   Compiling core-foundation v0.6.4
   Compiling security-framework-sys v0.3.3
   Compiling slog-async v2.3.0
   Compiling slog-scope v4.3.0
   Compiling tokio-timer v0.2.12
   Compiling tokio-current-thread v0.1.6
   Compiling rand_core v0.5.1
   Compiling bytes v0.4.12
   Compiling rand v0.3.23
   Compiling pairing v0.14.2 (https://github.com/LayerXcom/librustzcash?branch=zero-chain#2c196871)
   Compiling fixed-hash v0.3.2
   Compiling futures-cpupool v0.1.8
   Compiling mio v0.6.21
   Compiling clap v2.32.0
   Compiling parking_lot v0.10.0
   Compiling dirs v2.0.2
   Compiling wasmi-validation v0.1.0
   Compiling mime v0.2.6
   Compiling digest v0.6.2
   Compiling crypto-mac v0.4.0
   Compiling block-buffer v0.2.0
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling crypto-mac v0.7.0
   Compiling block-cipher-trait v0.6.2
   Compiling stream-cipher v0.3.2
   Compiling digest v0.7.6
   Compiling crypto-mac v0.5.2
   Compiling crossbeam-queue v0.2.1
   Compiling crossbeam-channel v0.4.0
   Compiling kvdb v0.1.0 (https://github.com/paritytech/parity-common?rev=b0317f649ab2c665b7987b8475878fc4d2e1f81d#b0317f64)
   Compiling regex v1.3.3
   Compiling backtrace v0.3.40
   Compiling security-framework v0.3.4
   Compiling wasm-timer v0.1.3
   Compiling rand_chacha v0.2.1
   Compiling cuckoofilter v0.3.2
   Compiling tokio-io v0.1.12
   Compiling http v0.1.21
   Compiling tokio-buf v0.1.1
   Compiling string v0.2.1
   Compiling mio-uds v0.6.7
   Compiling mio-extras v2.0.6
   Compiling synstructure v0.12.3
   Compiling wasm-bindgen-backend v0.2.58
   Compiling wasmi v0.4.5
   Compiling hyper v0.10.16
   Compiling hmac v0.4.2
   Compiling sha2 v0.6.0
   Compiling curve25519-dalek v1.2.3
   Compiling sha2 v0.8.1
   Compiling sha3 v0.8.2
   Compiling sha-1 v0.8.2
   Compiling ripemd160 v0.8.0
   Compiling hmac v0.7.1
   Compiling blake2 v0.8.1
   Compiling aes-soft v0.3.3
   Compiling twofish v0.2.0
   Compiling block-modes v0.3.3
   Compiling ctr v0.3.2
   Compiling blake2 v0.7.1
   Compiling trie-db v0.12.4
   Compiling console v0.9.1
   Compiling console v0.7.7
   Compiling env_logger v0.5.13
   Compiling synstructure v0.10.2
   Compiling substrate-panic-handler v1.0.0 (https://github.com/osuketh/substrate?branch=patch-zerochain#12f25052)
   Compiling chrono v0.4.10
   Compiling rand v0.7.2
   Compiling tokio-codec v0.1.1
   Compiling rw-stream-sink v0.1.2
   Compiling http-body v0.1.0
   Compiling h2 v0.1.26
   Compiling serde_derive v1.0.104
   Compiling asn1_der_derive v0.1.2
   Compiling proc-macro-hack v0.5.11
   Compiling neon-sys v0.3.3
   Compiling wasm-bindgen-macro-support v0.2.58
   Compiling ws v0.7.9
   Compiling zeroize_derive v1.0.0
   Compiling malloc_size_of_derive v0.1.1
   Compiling hmac-drbg v0.1.2
   Compiling pbkdf2 v0.3.0
   Compiling aes v0.3.2
   Compiling aes-ctr v0.3.0
   Compiling zerochain-pairing v0.14.2 (https://github.com/LayerXcom/zero-chain?branch=wallet-desktop#10b7f2e2)
   Compiling parking_lot v0.7.1
   Compiling srml-support-procedural-tools-derive v1.0.0 (https://github.com/osuketh/substrate?branch=patch-zerochain#12f25052)
   Compiling strum_macros v0.14.0
   Compiling libp2p-core-derive v0.8.0
   Compiling twox-hash v1.5.0
   Compiling tempfile v3.1.0
   Compiling unsigned-varint v0.2.3
   Compiling asn1_der v0.6.3
   Compiling paste-impl v0.1.6
   Compiling tokio-reactor v0.1.11
   Compiling aio-limited v0.1.1
   Compiling yamux v0.2.2
   Compiling failure v0.1.6
   Compiling zeroize v1.1.0
   Compiling zeroize_derive v0.9.3
   Compiling crossbeam-deque v0.7.2
   Compiling libsecp256k1 v0.2.2
   Compiling scrypt v0.2.0
   Compiling jubjub v0.1.0 (https://github.com/LayerXcom/zero-chain?branch=wallet-desktop#10b7f2e2)
   Compiling wasm-bindgen-macro v0.2.58
   Compiling once_cell v0.1.8
   Compiling parity-util-mem v0.1.0
   Compiling dialoguer v0.4.0
   Compiling parity-multihash v0.1.3
   Compiling multistream-select v0.4.0
   Compiling tokio-uds v0.2.5
   Compiling tokio-tcp v0.1.3
   Compiling tokio-udp v0.1.5
   Compiling paste v0.1.6
   Compiling curve25519-dalek v2.0.0
   Compiling merlin v1.3.0
   Compiling tokio-threadpool v0.1.17
   Compiling crossbeam v0.7.3
   Compiling x25519-dalek v0.5.2
   Compiling zeroize v0.9.3
   Compiling tiny-bip39 v0.6.2
   Compiling memory-db v0.12.4
   Compiling tokio-tls v0.2.1
   Compiling neon-runtime v0.3.3
   Compiling ed25519-dalek v1.0.0-pre.3
   Compiling tokio-fs v0.1.6
   Compiling toml v0.5.5
   Compiling impl-serde v0.2.3
   Compiling impl-serde v0.1.1
   Compiling parity-multiaddr v0.4.1
   Compiling serde_json v1.0.44
   Compiling serde_bytes v0.11.3
   Compiling bellman v0.1.0 (https://github.com/LayerXcom/librustzcash?branch=zero-chain#2c196871)
   Compiling schnorrkel v0.8.5
   Compiling parity-crypto v0.4.2
   Compiling js-sys v0.3.35
   Compiling websocket v0.22.4
   Compiling neon v0.3.3
   Compiling zerochain v0.1.0 (/Users/y.shiono/Documents/src/zerochain-wallet-desktop/zerochain/native)
   Compiling schnorrkel v0.1.1
   Compiling tokio v0.1.22
   Compiling libp2p-core v0.8.1
error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::CryptoRng` is not satisfied
   --> /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.8.1/src/identity/ed25519.rs:34:44
    |
34  |         Keypair(ed25519::Keypair::generate(&mut rand::thread_rng()))
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::CryptoRng` is not implemented for `rand::rngs::thread::ThreadRng`
    |
   ::: /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/ed25519.rs:130:12
    |
130 |         R: CryptoRng + RngCore,
    |            --------- required by this bound in `ed25519_dalek::ed25519::Keypair::generate`

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::RngCore` is not satisfied
   --> /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.8.1/src/identity/ed25519.rs:34:44
    |
34  |         Keypair(ed25519::Keypair::generate(&mut rand::thread_rng()))
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand::rngs::thread::ThreadRng`
    |
   ::: /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/ed25519.rs:130:24
    |
130 |         R: CryptoRng + RngCore,
    |                        ------- required by this bound in `ed25519_dalek::ed25519::Keypair::generate`

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::CryptoRng` is not satisfied
   --> /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.8.1/src/identity/ed25519.rs:141:48
    |
141 |         SecretKey(ed25519::SecretKey::generate(&mut rand::thread_rng()))
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::CryptoRng` is not implemented for `rand::rngs::thread::ThreadRng`
    |
   ::: /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/secret.rs:172:12
    |
172 |         T: CryptoRng + RngCore,
    |            --------- required by this bound in `ed25519_dalek::secret::SecretKey::generate`

error[E0277]: the trait bound `rand::rngs::thread::ThreadRng: rand_core::RngCore` is not satisfied
   --> /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.8.1/src/identity/ed25519.rs:141:48
    |
141 |         SecretKey(ed25519::SecretKey::generate(&mut rand::thread_rng()))
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^ the trait `rand_core::RngCore` is not implemented for `rand::rngs::thread::ThreadRng`
    |
   ::: /Users/y.shiono/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-1.0.0-pre.3/src/secret.rs:172:24
    |
172 |         T: CryptoRng + RngCore,
    |                        ------- required by this bound in `ed25519_dalek::secret::SecretKey::generate`

   Compiling proc-macro-crate v0.1.4
   Compiling slog-json v2.3.0
error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `libp2p-core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/y.shiono/Documents/src/zerochain-wallet-desktop/node_modules/neon-cli/lib/target.js:124:35)
    at step (/Users/y.shiono/Documents/src/zerochain-wallet-desktop/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/y.shiono/Documents/src/zerochain-wallet-desktop/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/y.shiono/Documents/src/zerochain-wallet-desktop/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
electron-build-env error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is my environment::

- Rust 1.40
- Python 2.x
- Node.js 10 (LTS)

Can anyone help me? 
If this issue resolves, probably I can bundle this app for production binaries :)

**Comment by osuketh** [comment]
Can you try `cargo update -p ed25519-dalek --precise v1.0.0-pre.2` at the directory where `Cargo.lock` generated.

**Comment by saltyshiomix** [comment]
@osuketh 

I got some warnings but anyway compiling is successful!

Thank you very much!

**Comment by saltyshiomix** [comment]
But note:

If re-run `yarn update-rust`, we got the same errors.
